# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.x

    - name: Set up protoc
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: protobuf-compiler
        version: 1.0

    - name: Set up protoc-gen-go
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go

    - name: Build
      run: make

    - name: Test
      run: make test
